AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for DynamoDB Table'

Resources:
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyTable
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: N
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  DynamoDBTableName:
    Value: !Ref MyDynamoDBTable