# Use an official lightweight Ubuntu base image
FROM ubuntu:22.04

# The recommended modern way is to use the LABEL instruction instead.
LABEL maintainer="Hello Wolrd<hello.world@example.com>"
LABEL version="1.0"
LABEL description="This is an example image showcasing metadata."

ARG buildno=1

WORKDIR /app

RUN echo "app directory contains : $(ls -la /app)"

RUN echo "Default diretory I am operating in is : $(pwd)"

COPY . /app

RUN echo "app directory contains : $(ls -la /app)"

RUN echo "user list before creating user : $(cat /etc/passwd)"

RUN echo "Operating user at this moment : $(whoami)"

# USER dtripat1

# RUN echo "Operating user at this moment : $(whoami)"
# RUN echo "user list after creating user : $(cat /etc/passwd)"

RUN echo "Build number is : $buildno"

EXPOSE 8080

# Update the package list and install curl
RUN apt-get update && apt-get install -y \
    curl \
 && rm -rf /var/lib/apt/lists/*

HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
  CMD curl --fail --silent --show-error http://localhost:8080/health || exit 1

  # Keeps the container alive forever
CMD ["sleep", "infinity"]